- name: Install Apache Web Server
  hosts: _prod_server  
  become: true  
  tasks:

    - name: Update yum package index (RedHat/CentOS)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"


    - name: Install Apache (RedHat/CentOS)
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Apache service (RedHat/CentOS)
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"